import { CourseDefinition } from './models';

export const ROLE_COURSES: CourseDefinition[] = [
  {
    slug: 'fhir-developer',
    title: 'FHIR Developer',
    role: 'Healthcare IT developers',
    level: 'Intermediate',
    category: 'Developer',
    duration: '8 weeks',
    studyHours: 32,
    prerequisites: 'Basic programming and HTTP knowledge',
    accent: '#1A6BB8',
    description: 'Build production-ready FHIR integrations, APIs, profiles, and SMART applications from first principles.',
    practicalOutcome: 'A working implementation plan for a secure FHIR application.',
    outcomes: ['Design and exchange FHIR resources', 'Build RESTful searches and integrations', 'Implement SMART, Bulk Data, and validation patterns'],
    phaseIds: [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 12, 13, 14, 15],
  },
  {
    slug: 'fhir-architect',
    title: 'FHIR Systems Architect',
    role: 'System architects',
    level: 'Advanced',
    category: 'Architect',
    duration: '10 weeks',
    studyHours: 40,
    prerequisites: 'Experience designing healthcare or enterprise systems',
    accent: '#7A4E2D',
    description: 'Shape interoperable health-information platforms with sound architecture, governance, security, and conformance.',
    practicalOutcome: 'An architecture blueprint for interoperable health-information exchange.',
    outcomes: ['Evaluate interoperability architecture choices', 'Plan profiles, terminology, and governance', 'Design secure enterprise exchange patterns'],
    phaseIds: [1, 2, 3, 9, 10, 11, 12, 13, 14, 16],
  },
  {
    slug: 'fhir-qa-testing',
    title: 'FHIR QA & Testing',
    role: 'Quality assurance and test engineers',
    level: 'Intermediate',
    category: 'QA & Testing',
    duration: '6 weeks',
    studyHours: 24,
    prerequisites: 'API testing fundamentals',
    accent: '#13795B',
    description: 'Validate FHIR implementations with repeatable API, resource, profile, terminology, and conformance testing.',
    practicalOutcome: 'A repeatable test strategy for a FHIR implementation.',
    outcomes: ['Build a FHIR validation strategy', 'Test APIs, profiles, searches, and terminology', 'Troubleshoot implementation failures systematically'],
    phaseIds: [0, 2, 3, 9, 10, 11, 13, 14, 15, 16],
  },
  {
    slug: 'fhir-project-leaders',
    title: 'FHIR for Project Leaders',
    role: 'Project managers and analysts',
    level: 'Foundational',
    category: 'Project Leadership',
    duration: '4 weeks',
    studyHours: 16,
    prerequisites: 'No technical prerequisites',
    accent: '#B85A12',
    description: 'Understand the technical decisions, delivery risks, and vocabulary behind successful FHIR programs.',
    practicalOutcome: 'A delivery roadmap with FHIR dependencies, risks, and milestones.',
    outcomes: ['Translate FHIR concepts into project decisions', 'Plan implementation milestones and dependencies', 'Identify security, data, and conformance risks'],
    phaseIds: [0, 1, 2, 3, 4, 9, 10, 12, 13, 16],
  },
  {
    slug: 'fhir-for-clinical-workflows',
    title: 'FHIR for Clinical Workflows',
    role: 'Healthcare professionals',
    level: 'Foundational',
    category: 'Clinical',
    duration: '5 weeks',
    studyHours: 20,
    prerequisites: 'Clinical workflow knowledge',
    accent: '#9B3D68',
    description: 'Gain a practical technical understanding of how FHIR represents patients, care, diagnostics, medications, and consent.',
    practicalOutcome: 'A shared vocabulary for discussing clinical interoperability with technical teams.',
    outcomes: ['Connect clinical workflows to FHIR resources', 'Read exchanged patient and clinical data', 'Understand privacy, consent, and safe interoperability'],
    phaseIds: [0, 1, 3, 4, 5, 6, 7, 8, 9, 12],
  },
];

export function courseBySlug(slug: string): CourseDefinition | undefined {
  return ROLE_COURSES.find((course: CourseDefinition) => course.slug === slug);
}
